name: Deploy Preview

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: latest

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build theme
        run: npm run build

      - name: Deploy
        env:
          SHOPIFY_FLAG_STORE: 'ypb-dev.myshopify.com'
          SHOPIFY_CLI_THEME_TOKEN: shptka_47d6d45c8fe7c3156650a4c1546a902a
          SHOPIFY_CLI_TTY: 0
        run: shopify theme push --path ./dist/ --theme 138189111469